# Generated by Django 5.0.6 on 2024-07-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_driver_id_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
